
FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json

COPY ./package*.json ./package*.json

COPY turbo.json turbo.json

COPY ./apps/web ./apps/web

RUN bun install


RUN --mount=type=secret,id=DB_URL \
    ls -la /run/secrets && \
    export DATABASE_URL=$(cat /run/secrets/DB_URL) && \
    echo "DATABASE_URL: $DATABASE_URL" && \
    bun install && \
    bun run db:generate && \
    bun run web:build

EXPOSE 3000

CMD [ "bun", "run", "start:web" ]