FROM oven/bun:1
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json

COPY ./package*.json ./package*.json

COPY turbo.json turbo.json

COPY ./apps/web ./apps/web

RUN bun install
COPY ./apps/web ./apps/web
# RUN bun db:migrate
RUN bun db:generate
RUN bun run build 




EXPOSE 3000

CMD [ "bun", "run", "start:web" ]