FROM oven/bun:1

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json

COPY ./package*.json ./package*.json

COPY turbo.json turbo.json


RUN bun install

COPY ./apps/web ./apps/web

RUN --mount=type=secret, id=DB_URL \
    export DATABASE_URL=$(cat /run/secrets/DB_URL) && \
    echo $DATABASE_URL && \
    bun db:generate && \
    bun run build

EXPOSE 3000

CMD [ "bun", "run", "start:web" ]